# Numpy, Pandas, Matplotlib, Seaborn

# Modules, packages and libraries

## Math module

In [1]:
# Without math:
pv = 100
f = 1.03
n = 2

fv = pv * f ** n
fv

106.08999999999999

In [2]:
# With math:
import math

fv = pv * math.pow(f, n)
fv

106.08999999999999

In [5]:
import math

math.sqrt(fv / pv) - 1

0.030000000000000027

In [4]:
# Or nicer (feels more functional):
from math import sqrt

sqrt(fv / pv) - 1

0.030000000000000027

## Numpy package

In [6]:
import numpy as np

np.sqrt(fv / pv)

1.03

In [7]:
pv * np.power(f, n)

106.08999999999999

# Numpy arrays (Numerical Python)

In [12]:
import numpy as np

cfs = [50, 100, 120, 150, 200, 300]
cfs

[50, 100, 120, 150, 200, 300]

In [15]:
type(cfs)

list

In [13]:
# Convert to numpy array
cfs_a = np.array(cfs)
cfs_a

array([ 50, 100, 120, 150, 200, 300])

In [14]:
type(cfs_a)

numpy.ndarray

In [16]:
# In-place changing of list elements is not nice and goes against FP.
# But with numpy arrays we can change and get a new copy at the same time i.e. not actually change the original.
cfs_a - 20

array([ 30,  80, 100, 130, 180, 280])

In [17]:
cfs

[50, 100, 120, 150, 200, 300]

In [18]:
cfs_a * 1.1

array([ 55., 110., 132., 165., 220., 330.])

In [20]:
cfs_a2 = np.array([10, 20, -10,30, 10, -5])

In [21]:
cfs_a + cfs_a2

array([ 60, 120, 110, 180, 210, 295])

In [22]:
# What are the types of the elements in our numpy array? Numpy arrays are homogeneous and only accept 1 data type i.e. no mixing.
cfs_a2.dtype

dtype('int64')